import { Role, ROLES } from "./roles";

export const PERMISSIONS = {
  CAN_MANAGE_USERS: [ROLES.ADMIN],
  CAN_CREATE_ARTICLE: [ROLES.ADMIN, ROLES.EDITOR],
  CAN_VALIDATE_ARTICLE: [ROLES.ADMIN, ROLES.EDITOR, ROLES.QA_ENGINEER],
  CAN_MANAGE_TEST_CASES: [ROLES.ADMIN, ROLES.QA_ENGINEER],
  CAN_EXECUTE_TESTS: [ROLES.ADMIN, ROLES.QA_ENGINEER],
  CAN_MANAGE_BUGS: [ROLES.ADMIN, ROLES.QA_ENGINEER],
  CAN_UPDATE_BUGS: [ROLES.ADMIN, ROLES.QA_ENGINEER, ROLES.EDITOR],
  CAN_VIEW_REPORTS: [ROLES.ADMIN, ROLES.QA_ENGINEER, ROLES.EDITOR, ROLES.VIEWER],
  CAN_USE_AI: [ROLES.ADMIN, ROLES.QA_ENGINEER, ROLES.EDITOR],
};

export function hasPermission(role: Role | undefined, allowedRoles: Role[]): boolean {
  if (!role) return false;
  return allowedRoles.includes(role);
}
